name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build application
      run: ./gradlew ciBuild
    - name: run unit tests
      run: ./gradlew ciUnitTests
    - name: start emulator
      run: ./start-emulator-macos-azure-build-agent.sh
    - name: run instumentation tests
      run: ./gradlew ciInstumentationTests
