name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build application
      run: ./gradlew ciBuild
    - name: run unit tests
      run: ./gradlew ciUnitTests
